In [31]:
import numpy as np
#

In [32]:
input_value = np.array([[0,0],[0,1],[1,1],[1,0]])
input_value.shape

(4, 2)

In [33]:
input_value

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [34]:
output_value = np.array([0,1,1,0])
output_value = output_value.reshape(4,1)

In [35]:
output_value.shape

(4, 1)

In [36]:
weights = np.array([[0.1],[0.2]])
weights

array([[0.1],
       [0.2]])

In [21]:
bias = 0.3

In [22]:
def sigmoid_func(x):
    return 1/(1+np.exp(-x))

In [23]:
def derv(x):
    return sigmoid_func(x) * (1-sigmoid_func(x))

In [37]:
for epochs in range(1000):
    input_arr = input_value
    
    weighted_sum = np.dot(input_arr,weights) + bias
    first_output = sigmoid_func(weighted_sum)
    
    error = first_output - output_value
    total_wrror = np.square(np.subtract(first_output,output_value)).mean()
    
    first_der = error
    second_der = derv(first_output)
    derivative = first_der*second_der
    
    t_input=input_value.T
    final_derivative = np.dot(t_input,derivative)
    
    weights = weights - 0.05*final_derivative
    
    for i in derivative:
        bias = bias - 0.05*i
        
    #print(epochs,weights,end=" ")
    #print(epochs,bias,end=" ")
    
print(weights)
print(bias)

[[-0.37371295]
 [ 4.30577231]]
[-1.8487973]


In [38]:
pred = np.array([0,1])

result = np.dot(pred,weights) + bias

res = sigmoid_func(result)

print(res)

[0.92107003]
